### PR TITLE
Fixes database init and adds instructions

### PR DESCRIPTION
**Pull request by bravo-kernel**
This PR adds the missing database init piece to the installation puzzle, including some fixes for the init itself, see commits.

### CODE REVIEW

**Comment by bravo-kernel** [comment]
I commented out `snapshots.sql` because the file is not in the repo. Should it be there?

**Comment by abchrisxyz** [comment]
Good catch. You can tell I never actually ran that init script and just used it to document what files needed to be loaded. Thanks for updating it.

Since `init.sql` should only ever be run on a fresh db, I don't think the `drop schema if exists` statements are needed. I had them commented out to avoid shooting myself in the foot when editing schemas, so would rather keep them that way. Happy to merge the rest though.

**Comment by bravo-kernel** [comment]
How about keeping things consistent so that they are predictable and easy to reason about, so:

- either a drop in every `.sql` file
- or no drops in any of them 

Reason I am saying is because current `oracle-pools.sql`, `sigma-usd.sql` and `sync.sql` files already have active drops so if I were to revert my suggestions we would end up with a mix where some files have a drop, some do not.  

Let me know how to proceed ok? 

> Another thing. **Did you see my question about `snapshots.sql`?** The file is mentioned in `_init.sql` but does not exist in the repo. Should it be there and is it required to get to a proper installation?

**Comment by abchrisxyz** [comment]
Right, you've got a point there. My preference would be to remove all `drop` statements. Only reason I had them in some files was for easier iteration over schema versions, but they have no use anymore really. Feel free to remove the remaining ones.

Didn't see you question about `snapshot.sql`, sorry. It was an earlier version of `metrics.sql`, not relevant anymore and should've been removed from `init.sql`.

**Comment by bravo-kernel** [comment]
Perfect, here it is 👍

**Comment by abchrisxyz** [comment]
👍 🙏

**Pull request merged**
